'use client'

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { useState } from "react";
import { twMerge } from "tailwind-merge";


const poppins = Poppins({
  weight: ["400", "700"], 
  subsets: ["latin"], 
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [menuActive, setMenuActive] = useState(false)

  return (
    <html lang="en">
      <body className={poppins.className}>
        {/* <Navbar/>
        <main className=" h-[calc(7000vh-88px)]">
        {children}
        </main>
        <Footer/> */}
        <header className="container mx-auto p-4 flex items-center gap-4">
          <div className="w-14 aspect-square bg-black" />
          <nav className={twMerge(
            "lg:flex flex-col md:flex-row gap-4 flex-1 justify-end absolute md:static top-24 items-center w-full",
            menuActive ? "flex" : "hidden"
          )}>
            <a href="https://google.com">google</a>
            <a href="https://facebook.com">facebook</a>
            <a href="https://instagram.com">instagram</a>
            <a href="https://twitter.com">twitter</a>
            <a href="https://telegram.com">telegram</a>
          </nav>
          <button className=" bg-black text-white p-2 ms-auto">Sign In</button>
          <button className=" bg-black text-white p-2 block md:hidden" onClick={() => setMenuActive(!menuActive)}>
            {menuActive ? <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" className="lucide lucide-x"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" className="lucide lucide-menu"><line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="18" y2="18"/></svg>}
          </button>
        </header>
      </body>
    </html>
  );
}
